version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ${BACKEND_FOLDER}/Dockerfile.dev
    volumes:
      - ${BACKEND_FOLDER}:/usr/app
    environment:
      NODE_ENV: development
