version: "3"

services:
  db:
    image: postgres:16-alpine
    shm_size: "2gb"
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  db_data:
