version: "3"

services:
  backend:
    restart: always
    ports:
      - ${APPLICATION_PORT}:8000
    environment:
      NODE_ENV: ${ENVIRONMENT}
      WORKDIR: /usr/app
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: scientilla
      DB_USER: scientilla
      DB_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    shm_size: "2gb"
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: scientilla
      POSTGRES_USER: scientilla
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  db_data:
